### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Ry-K**
Lib updates, optimistic versioning and some tests. Note the changes, esp. breaking, in the readme.

### CODE REVIEW

**Comment by tstojecki** [comment]
Thanks for this incredible body of work @Ry-K !
I have started testing and will get that merged to the dev branch after a quick test. I have seen a few comments on the breaking changes, so I will try to focus on those first. I will also get this tested against our solution to see what shakes out.

If you feel that it would be easier that way, I am happy to give you contributor's rights to the repo.

I will also need to figure out how we're going to go about publishing the nuget package. I may need to talk to the previous owner about this. We could just publish a new version under my account going forward. I would like to remove BmbSqd from the namespace and the assembly name, I think we can just go with ElasticIdentity as the root of the namespace.

**Comment by Ry-K** [comment]
You're welcome @tstojecki. I need to incorporate this into a small webapp in my personal time for some testing as well, but that might be a bit before I've got the time to do so.

I think it would be great if this project lived on in one location rather than at least 2 forks at the moment. But, there is some reasoning here as "ours" may diverge at some point. Let me think on this some more.

I noticed the .nuspec also with BmbSqd under the copyright. I figured I could just use a different .nuspec for our needs if/when they arise (and publish internally) but the disparity with the namespace is, while trivial, unhelpful. I'm in agreement on your suggestion, or any others with one caveat: the naming should be more open to reflect the public's contributions, past, present and future - this didn't use GA/release libraries for NEST/Elasticsearch.Net until other's patronage. Let me know what you end up with on this please.

Have a great weekend!

**Comment by Ry-K** [comment]
If you're willing as you mentioned, I would be happy to have contributors rights on your repo. That way I can just delete our fork (so this remains just 1 place); we don't have any pressing need for it.

I'll continue with updates to this PR until later.

Thanks @tstojecki .

**Comment by Ry-K** [comment]
Hi @tstojecki. Please let me know when you've got this merged in. I will have one more PR for you (optional cleanup/R# changes) and then I don't see much else barring any issues. Heard anything on the namespace?

**Comment by tstojecki** [comment]
Hi @Ry-K 
It was merged on Monday 
https://github.com/tstojecki/elastic-identity/commit/ae781ab86daf2bc9c036b1c8b3bb575835deeeda

Please go ahead with your other PR. I will be renaming the namespaces and the assembly to ElasticIdentity and then I will start working on publishing a nuget package.

**Comment by Ry-K** [comment]
Sorry, I wasn't clear @tstojecki, [this commit](https://github.com/Ascendon/elastic-identity/commit/2cb830cd5fb86ae57b4d2b20a6991df329127468)

**Comment by Ry-K** [comment]
If you are comfortable where things stand I am going to delete the fork from CSG/Ascendon and fork again under my personal.

Edit: I need to add; thanks for your help in testing and the renaming!

**Comment by tstojecki** [comment]
Sounds good Ryan,
I think I have merged in all your PRs at this point. 

I have published a few additional commits since:
- moved the tests to xunit, added runner as a package 
- cleaned up ctors, i will create an issue for that so we can discuss further
- exposed protected IElasticClient and removed what I though was a bit overcomplicated async/awaitable in Connection property

We're getting close, but I would like to get this tested and cleaned up a bit more before we throw it up on nuget. Please let me know if you can run the project and the tests after getting latest.

**Comment by tstojecki** [comment]
Also, I have tried adding you to the repo, but was unable to find by either github username or email. If you're interested, please let me know how I can find you.

**Comment by Ry-K** [comment]
My apologies; this is the response I missed before commenting last night (long day). I was "cloaked"...can you see me now?

**Comment by tstojecki** [comment]
Yes, you're a contributor now. 
If you decide to work on something, please make sure you have an issue assigned to you and I will do the same just so we don't overlap.

**Pull request merged**
